### PR TITLE
Finalize converting the project to Swift 3 and fix demo project

### PR DESCRIPTION
**Pull request by leolobato**
Also exposes the `status` from the recorder as read-only. Should be useful in production apps.

### CODE REVIEW

**Comment by fulldecent** [comment]
Thank you. Running this (and my other attempt) in the simulator gets a `nil` at

            let exportSession = AVAssetExportSession(asset: avAsset, presetName: AVAssetExportPresetAppleM4A)!

Is this working for you? Did it work in the simulator and/or on a real device. And what version have you tested on? I'll be happy to merge if it is working for other people.

**Comment by leolobato** [comment]
It works for me on my project both on device and on the Simulator, but when I'm testing the demo project it crashes missing asking for the `NSMicrophoneUsageDescription` Info.plist key.

Will fix that and rebase the PR.

**Comment by fulldecent** [comment]
Awesome, thanks for the reply and the contribution.

**Comment by leolobato** [comment]
OK, fixed now. It is working for me on iPhone 5 running iOS 9.3.5 and iPhone 6 running iOS 10.0.2.

Not sure why I can't print from the console the `exportSession` instance for that line when runnning on the device, but it does show up correctly on the Simulator (and it is actually working, so the instance is there).

**Comment by fulldecent** [comment]
Great, thank you. Merged.

**Pull request merged**
